baseURL = "https://elastic-pare-a6a5db.netlify.app"
languageCode = "en-us"
title = "Pabrik Lampu"
theme = "hugo-shopping-product-catalogue-simple"
themesDir = "../.."
[Params]
description = "Pabrik lampu keren"
